### ISSUE TITLE
Visiting https://treestatus.mozilla-releng.net redirects to /static/ui/treestatus/, but doesn't load correctly

### ISSUE THREAD

**Issue by emilio** [mozilla-releng/treestatus#31] opened 2021-03-03 13:07 UTC
If you visit https://treestatus.mozilla-releng.net/, it redirects to /static/ui/treestatus using JS, but it doesn't seem to ever finish load. If you then refresh the page it works.

It happens on all browsers so it seems like a site issue.

**Comment by Archaeopteryx** [comment] 2021-03-03 13:11
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1638816

**Comment by jcristau** [comment] 2024-06-17 12:37
Treestatus migrated to lando (https://bugzilla.mozilla.org/show_bug.cgi?id=1771695), closing remaining issues on this repo.

**Closed by jcristau** 2024-06-17 12:37 UTC
